app:
  github-api-uri: https://api.github.com
  stackoverflow-api-uri: https://api.stackexchange.com/2.3
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 300s
  bot-api-uri: http://localhost:8090

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
  liquibase:
    enabled: false

server:
  port: 9191

logging:
  config: classpath:log4j2-plain.xml

springdoc.swagger-ui.path: /swagger-ui
