app:
  github-api-uri: https://api.github.com
  stackoverflow-api-uri: https://api.stackexchange.com/2.3
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  bot-api-uri: http://localhost:8090

spring:
  application:
    name: scrapper

server:
  port: 9191

logging:
  config: classpath:log4j2-plain.xml

springdoc.swagger-ui.path: /swagger-ui
