app:
  github-api-uri: https://api.github.com
  stackoverflow-api-uri: https://api.stackexchange.com/2.3
  scheduler:
    enable: true
    interval: 60s
    force-check-delay: 100s
  bot-api-uri: http://localhost:8090
  database-access-type: jooq
  use-queue: true
  limit:
    tokens: 1000
    interval: 1h
  retry:
    backoff: linear
    limit: 4
    interval: 2
    codes: 500, 404
    max-interval: 40
  kafka:
    servers: localhost:9092,localhost:9093,localhost:9094
    trusted-packages: edu.java.dto
    consumer-group: messages-group
    updates-topic: updates.json
    ack-mode: all

spring:
  application:
    name: scrapper
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
  liquibase:
    enabled: false
server:
  port: 9191

logging:
  config: classpath:log4j2-plain.xml

springdoc.swagger-ui.path: /swagger-ui
